name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your repo
      - uses: actions/checkout@v3

      # 2) Pin Node for consistency
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install & Build YOUR React app with the API base injected
      - name: Install dependencies
        working-directory: ./funding_navigator_frontend
        run: npm install

      - name: Create production build
        working-directory: ./funding_navigator_frontend
        # **⇦ Add your API base here so CRA bakes it into the bundle**
        env:
          REACT_APP_API_BASE: https://fn-navigator-api-app.azurewebsites.net
        run: npm run build

      # 4) Push that already-built bundle to SWA
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                ${{ secrets.GITHUB_TOKEN }}
          action:                    upload
          app_location:              "/" 
          app_artifact_location:     "funding_navigator_frontend/build"
