name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main     # or whatever branch you deploy from

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      # 1) Grab your code
      - uses: actions/checkout@v3

      # 2) (Optional) ensure Node is the right version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Build & deploy via the SWA action
      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # auto-populated when you first connected the SWA in GitHub
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # standard GitHub token for the checkout step
          repo_token:                ${{ secrets.GITHUB_TOKEN }}
          action:                    upload

          # ← POINT THESE AT YOUR CRA SUBFOLDER:
          app_location:              funding_navigator_frontend
          api_location:              ""          # no Azure Functions here
          output_location:           build       # relative to the app_location

        env:
          # this will become process.env.REACT_APP_API_BASE in your app
          REACT_APP_API_BASE: https://fn-navigator-api-app.azurewebsites.net
