name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          # this will be injected into your React code at build time
          REACT_APP_API_BASE: https://fn-navigator-api-app.azurewebsites.net
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                       ${{ secrets.GITHUB_TOKEN }}
          action:                           upload

          # ← this is the folder where package.json, src/, public/ live
          app_location:                     funding_navigator_frontend

          # ← you don’t have any Azure Functions in this repo
          api_location:                     ""

          # ← CRA writes its output here *inside* app_location
          output_location:                  build
