name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      # 1) pull your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) pin Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) install & build your React app (inject API base)
      - name: Install dependencies
        working-directory: ./funding_navigator_frontend
        run: npm ci

      - name: Build production bundle
        working-directory: ./funding_navigator_frontend
        env:
          # ← This bakes it into CRA at build time
          REACT_APP_API_BASE: https://fn-navigator-api-app.azurewebsites.net
        run: npm run build

      # 4) push the pre-built static assets directly into your SWA
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          # path **to** your built files
          app_artifact_location: funding_navigator_frontend/build
