name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # This secret is added automatically when you first create the SWA in GitHub
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # Standard GitHub token for checkout
          repo_token:                ${{ secrets.GITHUB_TOKEN }}
          action:                    upload

          # ◀── PATH TO YOUR REACT APP
          app_location:              funding_navigator_frontend

          # ◀── no Azure Functions in this repo
          api_location:              ""

          # ◀── after build, SWA will look here for the static assets
          output_location:           funding_navigator_frontend/build

          # ◀── inject your API base URL into the frontend at build time
          env:
            REACT_APP_API_BASE:      https://fn-navigator-api-app.azurewebsites.net
