# .github/workflows/azure-static-web-apps.yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build & Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                ${{ secrets.GITHUB_TOKEN }}
          action:                    "upload"
          # where your CRA project lives
          app_location:              "funding_navigator_frontend"
          # after Oryx builds, it copies the CRA /build into /app, so point here:
          output_location:           ""
        env:
          # this tells React where your API lives at runtime
          REACT_APP_API_BASE: "https://fn-navigator-api-app.azurewebsites.net"
