name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your code
      - uses: actions/checkout@v3

      # 2) Ensure Node is available
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install & build inside your actual React folder
      - name: Install dependencies and build
        working-directory: ./funding_navigator_frontend
        run: |
          npm install
          npm run build

      # 4) Deploy the build output to SWA
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                        ${{ secrets.GITHUB_TOKEN }}
          action:                            upload
          app_location:                      "funding_navigator_frontend"          
          output_location:                   "funding_navigator_frontend/build"  
        env:
          REACT_APP_API_BASE: "https://fn-navigator-api-app.azurewebsites.net"
