name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # this secret is set for you by Azure when you ran `az staticwebapp create`
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # GitHub token for the action
          repo_token:                ${{ secrets.GITHUB_TOKEN }}
          # upload = push your already-built files
          action:                    "upload"
          # where your package.json / src / public live
          app_location:              "funding_navigator_frontend"
          # where create-react-app spits out the final static assets
          output_location:           "funding_navigator_frontend/build"
        env:
          # point your frontend at your API
          REACT_APP_API_BASE: "https://fn-navigator-api-app.azurewebsites.net"
