name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # auto-created when you connected the repo to your SWA
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # standard GitHub checkout token
          repo_token:                ${{ secrets.GITHUB_TOKEN }}
          action:                    upload

          # ── relative path *inside* your repo where package.json lives
          app_location:              funding_navigator_frontend

          # ── you don’t have any Azure Functions here
          api_location:              ""

          # ── *inside* the app_location, that’s where npm run build drops index.html
          output_location:           build

          # ── inject your FastAPI URL into process.env at build time
          env: |
            REACT_APP_API_BASE=https://fn-navigator-api-app.azurewebsites.net
