name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and deploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          # This will be injected into your React build as process.env.REACT_APP_API_BASE
          REACT_APP_API_BASE: "https://fn-navigator-api-app.azurewebsites.net"
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                         ${{ secrets.GITHUB_TOKEN }}    # for GitHub integrations
          action:                             "upload"

          # ───── paths ─────
          # Location of your frontend source (where package.json lives)
          app_location:       funding_navigator_frontend

          # Leave this blank so the action deploys the default Oryx build output
          output_location:    ""
