name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main    # ← or whatever branch you deploy from

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          # this becomes process.env.REACT_APP_API_BASE in your React code
          REACT_APP_API_BASE: "https://fn-navigator-api-app.azurewebsites.net"
        with:
          # auto‐populated when you first connected the SWA in GitHub
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # for checkout
          repo_token:                     ${{ secrets.GITHUB_TOKEN }}
          action:                         "upload"

          # ──────── PATHS ───────────────────────────────────
          # where your CRA's package.json / src / public live
          app_location:                   "funding_navigator_frontend"

          # you have no Azure Functions in this repo
          api_location:                   ""

          # where CRA spits out the compiled assets (relative to app_location)
          output_location:                "build"
