name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # auto-created when you connected your repo to the SWA in Azure
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # for the checkout step
          repo_token:                ${{ secrets.GITHUB_TOKEN }}
          action:                    upload

          ## ── Where your CRA app lives in the repo:
          app_location:              funding_navigator_frontend

          ## ── No Azure Functions in this repo:
          api_location:              ''

          ## ── After npm run build, Oryx will drop your files under <app_location>/build,
          ##    and this tells it to look there:
          output_location:           build

          ## ── Inject your API URL at build time:
          env: |
            REACT_APP_API_BASE=https://fn-navigator-api-app.azurewebsites.net
