name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # auto-created secret
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                ${{ secrets.GITHUB_TOKEN }}
          action:                    upload

          # ◀── your CRA app folder
          app_location:              funding_navigator_frontend

          # ◀── no Functions here
          api_location:              ''

          # ◀── where Oryx will drop the built files
          output_location:           funding_navigator_frontend/build

          # ◀── block scalar to inject env var
          env: |
            REACT_APP_API_BASE=https://fn-navigator-api-app.azurewebsites.net
