name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and deploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          # will be available inside React as process.env.REACT_APP_API_BASE
          REACT_APP_API_BASE: "https://fn-navigator-api-app.azurewebsites.net"
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}   # for PR comments etc.
          action: "upload"

          # ───── paths ─────
          # where the package.json lives
          app_location: funding_navigator_frontend

          # leave this BLANK so we deploy whatever Oryx put at /app
          output_location: ""        # <= THIS is the critical change

