name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build And Deploy
        # inject your React build‐time env var here, at the STEP level
        env:
          REACT_APP_API_BASE: https://fn-navigator-api-app.azurewebsites.net

        uses: Azure/static-web-apps-deploy@v1
        with:
          # ← your SWA API token (set automatically by Azure)
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # ← standard GitHub token for checkout
          repo_token:                ${{ secrets.GITHUB_TOKEN }}

          # ← upload only (no “github_id_token” nonsense)
          action:                    upload

          # ── your CRA app lives in the repo root:
          app_location:              .

          # ── you have no Azure Functions in this repo:
          api_location:              ""

          # ── CRA’s `npm run build` writes into ./build
          output_location:           build
